apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server-github
  labels:
    app: python-server-app
spec:
  selector:
    matchLabels:
        app: python-server-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-server-app
    spec:
      containers:
        - name: python-server-app
          image: demo-image-name
          env:
          - name: S3_BUCKET_NAME
            value: "cnappdemo"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
